travis:
  secure:
    BINSTAR_TOKEN: W5IRnNQHafDyJ6BcmiwwaEVNkLHTX/6yZqcBrEIEmVyy7mZr23e77Er0px75gPWMpRlFYMzjFPi9eEEzVd4T/nbWvwGfl6YNDFHpdrDt5yFkoEg4QtS/E7qwBAHykJbl5wyZEJkLa2VU7odal81Awer1COijg5kX8mqmmw9oDAsZ+yQBgDI8N6NelAxXsSVHyjL+PpFoYH42r0yHEQJapjSYHWeuI6awmykDn9i0Tyi3oxFe2A00tMBCkJtBguMZaVoZmxkQP4qYe4zAsmASk83wm7MTWjaTBvBod6uZ2uB9Ybq9APNa6psurJ0wvMbGvhA4mBgtp9P4YpGTT/RG66YKXzdNuo3w4sDuzbWyDaW+00L0UbNKF6JUCQSBL2T9i7L3IrG0BaBK7TO6HGf7JXGM+N2czZxuXTDAwIyeN6T8xZXM2Nd2Q95mJ1Rlxrl/u4W4c5GaLV0s0v8v1Lvxyr396NQzx5xfbLpPXqDDls+BLaxQ7upTI2FIpTSZjO6DDV3vOtbyLH6EvKDKLRznuYF11w1OB9xSaottYFlcv4IZfcllOJuqewB7XlNRmUk3aztfLrH7q2Loy9RaS8RpD153YOmcbTRYQ8ajgchtzEeVbqYpADuiXd3rHWxqXrDpNGjj2T7TBIREemF2eqprP9K5H6dLaKFjySKE/iadQ0g=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
